language: minimal

services:
  - docker

env:
  global:
    - AWS_REGION=us-east-1
    - AWS_ACCOUNT_ID=160505104229
    - IMAGE_NAME=trial image
    - CLUSTER_NAME=trial cluster
    - TASK_FAMILY=cypress
    - TASK_CONTAINER_NAME=cyp_con
    - MONGODB_URI=mongodb+srv://krishnanaikedu:Kr1$hna@789@trialcluster.iqxzoko.mongodb.net/?retryWrites=true&w=majority

before_install:
  - echo "Installing AWS CLI and ECS CLI"
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - sudo pip install awscli --upgrade
  - sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
  - sudo chmod +x /usr/local/bin/ecs-cli

script:
  - echo "Building Docker image and pushing to ECR"
  - docker build -t $IMAGE_NAME .
  - $(aws ecr get-login --no-include-email)
  - docker tag $IMAGE_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME
  - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME

deploy:
  - provider: script
    script: |
      echo "Creating Fargate cluster and starting task"
      aws ecs create-cluster --cluster-name $CLUSTER_NAME
      TASK_DEFINITION=$(printf '{"family":"%s","containerDefinitions":[{"name":"%s","image":"%s","portMappings":[{"containerPort":3000}]}],"networkMode":"awsvpc","cpu":"256","memory":"512"}' $TASK_FAMILY $TASK_CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME)
      echo $TASK_DEFINITION > task-definition.json
      ecs-cli configure --region $AWS_REGION --cluster $CLUSTER_NAME
      ecs-cli compose --project-name $TASK_FAMILY service up --create-log-groups --task-definition task-definition.json
    on:
      branch: master

after_deploy:
  - echo "Integrating Fargate cluster with MongoDB Atlas"
  - ecs-cli configure --region $AWS_REGION --cluster $CLUSTER_NAME
  - ecs-cli compose --project-name $TASK_FAMILY service ps
  - TASK_ID=$(ecs-cli compose --project-name $TASK_FAMILY service ps | grep RUNNING | awk '{print $2}')
  - echo "Task ID: $TASK_ID"
  - ecs-cli configure --region $AWS_REGION --cluster $CLUSTER_NAME
  - ecs-cli run-task --task-definition $TASK_FAMILY --overrides '{"containerOverrides":[{"name":"'$TASK_CONTAINER_NAME'","environment":[{"name":"MONGODB_URI","value":"'$MONGODB_URI'"}]}]}' --launch-type FARGATE --count 1
